# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: PR_ON_Master_fastlane

on:
  pull_request:
    branches:
      - main

jobs:
    test:
        runs-on: macos-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Fastlane Tests
          run: fastlane tests
