# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: PR_ON_Master

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Xcode
          uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: '14.2'

        - name: Build and Test
          run: xcodebuild test -project SUnitTestAutomation.xcodeproj -scheme SUnitTestAutomation -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'
