# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: PR_ON_Master

on:
  push:
    branches:
      - main

jobs:
    test:
        runs-on: macos-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Xcode
          uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: latest-stable

        - name: Show macOS Version
          run: sw_vers

        - name: Run swiftlint
          run: swiftlint
      
        - name: Show Xcode Version
          run: xcodebuild -version

        - name: Run Unit Tests
          run: xcodebuild test -project SUnitTestAutomation.xcodeproj -scheme SUnitTestAutomation -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.2'
